<a href="https://colab.research.google.com/github/NishigandhaChoudhury/Neural-Network/blob/main/NNDLLab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
x=np.array(15)
print(x)

15


In [27]:
print(x.ndim)

0


In [28]:
vec = [11, 22, 33, 44, 55]
print(vec)

[11, 22, 33, 44, 55]


In [29]:
x= [2,3,4]
for element in x:
  print(element)

2
3
4


In [30]:
x = [5, 10, 15]
for i, val in enumerate(x):
    print(f"Index {i}: {val}")

Index 0: 5
Index 1: 10
Index 2: 15


In [31]:
x=np.array([2,3,4])
print(x)
print(x.ndim)
print(x.shape)

[2 3 4]
1
(3,)


In [32]:
x=np.array([2,6,4,9])

In [33]:
print(x)
print(x.ndim)

[2 6 4 9]
1


In [34]:
import numpy as np
x=np.array([[2,3,4],[6,7,8],[10,11,12],[3,12,11]])
print(x)
print(x.ndim)
print(x.shape)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [ 3 12 11]]
2
(4, 3)


In [14]:
import numpy as np

In [36]:
x = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [35]:
print(x.ndim)
print(x.shape)

2
(4, 3)


In [12]:
x=np.array([[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[3,4,5],[4,5,6],[6,7,8]]])
print(x)
print(x.ndim)
print(x.shape)

[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 6  7  8]]]
3
(4, 3, 3)


In [38]:
x = np.random.rand(67, 22, 29, 11)
print(x.ndim)
print(x.shape)

4
(67, 22, 29, 11)


In [17]:
import tensorflow as tf

In [39]:
string_tensor = tf.constant(["My", "name", "is Nishigandha"])

In [23]:
string_length = tf.strings.length(string_tensor)
print("String Lengths:", string_length.numpy())

String Lengths: [ 2  4 14]


In [40]:
import tensorflow as tf
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [42]:
x = np.array([67,45,24,98])
print(x.reshape(1,4))
print(x.reshape(4,1))

[[67 45 24 98]]
[[67]
 [45]
 [24]
 [98]]
